<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Detail</name>
   <tag></tag>
   <elementGuidId>aad28cd8-8296-4eb7-87b7-14c6613f688a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[3]/div/div/div/div/div/table/tbody[21]/tr/td[7]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d47e7777-24a0-468f-a465-3a0eec8b8a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-md btn-primary</value>
      <webElementGuid>225bf4fa-f51a-421b-bf3e-640c740aefda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Detail_Petani.php?id=user12315</value>
      <webElementGuid>01701bda-e56a-4f56-a3cd-185d562ce954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>30b17271-c40b-4196-ac47-f6c06ab5e437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;scroll&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;table&quot;]/tbody[21]/tr[1]/td[7]/a[@class=&quot;btn btn-md btn-primary&quot;]</value>
      <webElementGuid>882d3a00-5074-40a4-b8c8-a33e08e35d14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[3]/div/div/div/div/div/table/tbody[21]/tr/td[7]/a</value>
      <webElementGuid>a51ee2a5-7e21-4ae0-94be-bb54f4685aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Detail')])[22]</value>
      <webElementGuid>23f99b1f-92d3-4f05-9905-b63ee0be2272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BANCAK'])[1]/following::a[1]</value>
      <webElementGuid>11869ef1-8ff7-470e-839c-e97977cbf1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GUNUNG WUNGKAL'])[1]/following::a[1]</value>
      <webElementGuid>d6f28cc6-8545-494e-b235-2887f8b25558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[21]/preceding::a[1]</value>
      <webElementGuid>c77cd0b1-75fc-4a85-9d74-90e29b44ea7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Detail_Petani.php?id=user12315')]</value>
      <webElementGuid>76c6d155-f15b-4ced-877e-494f6b257486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody[21]/tr/td[7]/a</value>
      <webElementGuid>9adc91f0-3273-4d19-b620-3b4905d18e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Detail_Petani.php?id=user12315' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>e45c6f23-ee67-46d5-bde8-958f483a720f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
