<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Petani_alamat_petani</name>
   <tag></tag>
   <elementGuidId>44576929-149f-41fb-8a07-a4575ff930e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='alamat_petani']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;alamat_petani&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07de8c1e-25ce-4713-9a6e-b622382fe1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec780516-b7d0-4ce5-8533-f2600fad7da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat_petani</value>
      <webElementGuid>0612c0ba-5d8d-4773-8270-54e4648b31be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2df0cd7f-48cf-4a7d-b1a7-06985286b1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Alamat Petani</value>
      <webElementGuid>7201dbdd-d01b-4469-b4d0-b7a11cd5e603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4c6307c4-edf0-4511-bdad-5c0393326ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group has-feedback&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>9ece38ca-9d9a-4965-88b9-f7c9788a2bac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='alamat_petani']</value>
      <webElementGuid>ac9f46b6-0284-404c-b1de-1ad0560f1e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[5]/input</value>
      <webElementGuid>8251a4ae-1c64-4083-baca-bddff7390488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>638a9c0f-7ca8-4869-9edb-c5ae7cfc38ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'alamat_petani' and @type = 'text' and @placeholder = 'Alamat Petani']</value>
      <webElementGuid>2e9319c5-fbaf-4a35-a0f1-d85f98225711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
