<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cetak Daftar_cari</name>
   <tag></tag>
   <elementGuidId>dd312f7f-cc4a-476f-b1a2-3e288d317216</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cari']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cari&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1773ac6-c7d0-471c-a3a0-d1bfb2d25303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7af0776a-9c02-420c-a412-97237dc7501e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cari</value>
      <webElementGuid>0a738685-d960-4108-a412-e746580c038a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>e0146789-6cd0-4a1d-80ae-959ecc13448b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-md btn-primary</value>
      <webElementGuid>4ad567fb-03f7-4c48-ab71-671c2a7f7628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>margin</name>
      <type>Main</type>
      <value>6px;</value>
      <webElementGuid>e0aa00e5-8c57-48a3-b8ad-fffe30d79870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50px;</value>
      <webElementGuid>1e357440-41a6-41c3-b41f-d53c86773a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-11&quot;]/div[1]/form[1]/input[@class=&quot;btn-md btn-primary&quot;]</value>
      <webElementGuid>95025e7b-606b-4f15-9af5-7c9bfbf895e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cari']</value>
      <webElementGuid>eeb4b80e-d190-420b-bb46-3bb99f2e3930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/div/div/div/div/form/input[2]</value>
      <webElementGuid>d3a0718d-ad79-4a37-864e-c12d42be92f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>768ef1c3-6ef6-4c8d-931e-8cdf87be6184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'cari']</value>
      <webElementGuid>63fcbd1a-2a95-495c-b5fa-23de8561114b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
