<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SD                                  _d31312</name>
   <tag></tag>
   <elementGuidId>c0b6c444-8425-4ccf-9e23-8ae2fa2e030e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='pendidikan_terakhir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;pendidikan_terakhir&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9ebbb77b-1e54-4392-9017-68f5802894f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2804e077-42cb-40a1-b399-466b68135d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pendidikan_terakhir</value>
      <webElementGuid>c56c8772-56e5-420d-b566-a24790602295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                </value>
      <webElementGuid>de38873d-2eb1-45ad-a835-476d23d6e37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demoForm&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-group&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>cab50665-97b6-4774-b1ad-7062b4de672f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='pendidikan_terakhir']</value>
      <webElementGuid>97fcaf7a-8b86-4dc6-898e-908ab9b2c3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div[3]/select</value>
      <webElementGuid>ea78e72b-e5ba-4fa1-8aad-a424216e9c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Terakhir'])[1]/following::select[1]</value>
      <webElementGuid>8658ae66-4b89-411a-a46b-2b20727a41ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/following::select[1]</value>
      <webElementGuid>4b247a94-56f5-4402-a97b-1024c970bc35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Lahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>e71d6259-4995-467a-af00-415f707b9f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Tanggungan *'])[1]/preceding::select[1]</value>
      <webElementGuid>397d4514-bc79-4b49-a26a-97f0be1361f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>3676c6d9-45e7-4368-8e6a-b69ba1e479da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pendidikan_terakhir' and (text() = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ' or . = '
                                    SD
                                    SMP
                                    SMA
                                    D1
                                    D2
                                    D3
                                    S1
                                    S2
                                    S3
                                ')]</value>
      <webElementGuid>5b7b1a48-b415-4044-af50-06dbfe407e2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
