<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KabupatenKABUPATEN BANJARNEGARAKABUP_53d19e</name>
   <tag></tag>
   <elementGuidId>144b7333-4622-4777-a59d-92cb0b337499</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kab']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c7a3bcd5-1c0f-4a2b-9da9-8d497b393b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4e67ba5a-7335-4c57-b395-7705ce1d7074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kab</value>
      <webElementGuid>00ce2af0-58d1-44b0-be0a-620041acdb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kabupaten</value>
      <webElementGuid>46e2dd89-5102-4002-a0f4-b461525f3b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KabupatenKABUPATEN BANJARNEGARAKABUPATEN BANYUMASKABUPATEN BATANGKABUPATEN BLORAKABUPATEN BOYOLALIKABUPATEN BREBESKABUPATEN CILACAPKABUPATEN DEMAKKABUPATEN GROBOGANKABUPATEN JEPARAKABUPATEN KARANGANYARKABUPATEN KEBUMENKABUPATEN KENDALKABUPATEN KLATENKABUPATEN KUDUSKABUPATEN MAGELANGKABUPATEN PATIKABUPATEN PEKALONGANKABUPATEN PEMALANGKABUPATEN PURBALINGGAKABUPATEN PURWOREJOKABUPATEN REMBANGKABUPATEN SEMARANGKABUPATEN SRAGENKABUPATEN SUKOHARJOKABUPATEN TEGALKABUPATEN TEMANGGUNGKABUPATEN WONOGIRIKABUPATEN WONOSOBOKOTA MAGELANGKOTA PEKALONGANKOTA SALATIGAKOTA SEMARANGKOTA SURAKARTAKOTA TEGAL</value>
      <webElementGuid>6f3e6e34-5b27-4202-a016-dc0649cebb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kab&quot;)</value>
      <webElementGuid>47b7792e-8466-4bb4-988b-2d6f31cbc163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kab']</value>
      <webElementGuid>e064850e-7871-478b-8bb0-bfad63d1c4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div/select</value>
      <webElementGuid>09dff2ee-dfee-4c89-a85a-42b0819f1114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[1]</value>
      <webElementGuid>0903c818-bda2-41cb-9a46-fdc88206b1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi *'])[1]/following::select[2]</value>
      <webElementGuid>51898f85-cbba-49fd-bb5f-92efc66d6d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/preceding::select[1]</value>
      <webElementGuid>4eef820e-da59-496f-8dc0-ffb72a08a8c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[2]</value>
      <webElementGuid>7a8fd8c8-bede-48c0-ac61-6660c008cb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/select</value>
      <webElementGuid>2191febd-6d7a-45ef-9ee6-2105ddb5d20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kab' and @name = 'Kabupaten' and (text() = 'KabupatenKABUPATEN BANJARNEGARAKABUPATEN BANYUMASKABUPATEN BATANGKABUPATEN BLORAKABUPATEN BOYOLALIKABUPATEN BREBESKABUPATEN CILACAPKABUPATEN DEMAKKABUPATEN GROBOGANKABUPATEN JEPARAKABUPATEN KARANGANYARKABUPATEN KEBUMENKABUPATEN KENDALKABUPATEN KLATENKABUPATEN KUDUSKABUPATEN MAGELANGKABUPATEN PATIKABUPATEN PEKALONGANKABUPATEN PEMALANGKABUPATEN PURBALINGGAKABUPATEN PURWOREJOKABUPATEN REMBANGKABUPATEN SEMARANGKABUPATEN SRAGENKABUPATEN SUKOHARJOKABUPATEN TEGALKABUPATEN TEMANGGUNGKABUPATEN WONOGIRIKABUPATEN WONOSOBOKOTA MAGELANGKOTA PEKALONGANKOTA SALATIGAKOTA SEMARANGKOTA SURAKARTAKOTA TEGAL' or . = 'KabupatenKABUPATEN BANJARNEGARAKABUPATEN BANYUMASKABUPATEN BATANGKABUPATEN BLORAKABUPATEN BOYOLALIKABUPATEN BREBESKABUPATEN CILACAPKABUPATEN DEMAKKABUPATEN GROBOGANKABUPATEN JEPARAKABUPATEN KARANGANYARKABUPATEN KEBUMENKABUPATEN KENDALKABUPATEN KLATENKABUPATEN KUDUSKABUPATEN MAGELANGKABUPATEN PATIKABUPATEN PEKALONGANKABUPATEN PEMALANGKABUPATEN PURBALINGGAKABUPATEN PURWOREJOKABUPATEN REMBANGKABUPATEN SEMARANGKABUPATEN SRAGENKABUPATEN SUKOHARJOKABUPATEN TEGALKABUPATEN TEMANGGUNGKABUPATEN WONOGIRIKABUPATEN WONOSOBOKOTA MAGELANGKOTA PEKALONGANKOTA SALATIGAKOTA SEMARANGKOTA SURAKARTAKOTA TEGAL')]</value>
      <webElementGuid>c8415579-49e2-4776-a6fd-ff1bd73c8ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
