<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_KecamatanSUKOLILOKAYENTAMBAKROMOWINO_a51879</name>
   <tag></tag>
   <elementGuidId>98bfb381-e7fa-4cc8-aac9-9a0bfaff5720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Kec']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Kec</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98f611f0-4052-4291-842c-65b7f1ec9808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1a403111-534b-4e02-bb2a-47d5461dc566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Kec</value>
      <webElementGuid>24e04075-76b4-45c1-a331-17a987ac0804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>bdcbbf5c-1eac-4ec1-bf9f-ffe8100af632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KecamatanSUKOLILOKAYENTAMBAKROMOWINONGPUCAKWANGIJAKENBATANGANJUWANAJAKENANPATIGABUSMARGOREJOGEMBONGTLOGOWUNGUWEDARIJAKSATRANGKILMARGOYOSOGUNUNG WUNGKALCLUWAKTAYUDUKUHSETI</value>
      <webElementGuid>b76bcc74-d51c-4db7-a4b3-ecf0ff29d0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Kec&quot;)</value>
      <webElementGuid>397942c0-96d9-4535-bf5a-30f79b82738e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Kec']</value>
      <webElementGuid>eae3b891-d0a1-4190-bc61-99d84ee224c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='demoForm']/div[7]/div/div[2]/select</value>
      <webElementGuid>da799e0a-d307-4836-afd7-fc9efb24c8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kecamatan *'])[1]/following::select[1]</value>
      <webElementGuid>d08c01bf-320c-4e46-bc31-da77508dab67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten *'])[1]/following::select[2]</value>
      <webElementGuid>0bd15b8a-ec03-4a10-9f5f-3218b8ba7696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Desa / Kelurahan *'])[1]/preceding::select[1]</value>
      <webElementGuid>9a44c4b9-9f92-4815-a154-1948867206fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon *'])[1]/preceding::select[2]</value>
      <webElementGuid>d10c800a-5f2f-4962-a819-a72000226b60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>c81867f7-e178-4665-9b4f-e402b6af7ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Kec' and @name = 'Kecamatan' and (text() = 'KecamatanSUKOLILOKAYENTAMBAKROMOWINONGPUCAKWANGIJAKENBATANGANJUWANAJAKENANPATIGABUSMARGOREJOGEMBONGTLOGOWUNGUWEDARIJAKSATRANGKILMARGOYOSOGUNUNG WUNGKALCLUWAKTAYUDUKUHSETI' or . = 'KecamatanSUKOLILOKAYENTAMBAKROMOWINONGPUCAKWANGIJAKENBATANGANJUWANAJAKENANPATIGABUSMARGOREJOGEMBONGTLOGOWUNGUWEDARIJAKSATRANGKILMARGOYOSOGUNUNG WUNGKALCLUWAKTAYUDUKUHSETI')]</value>
      <webElementGuid>72f16ec7-6390-4d51-ac88-7a61fe65518e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
